import type { Metadata } from "next";
import { Darker_Grotesque } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Navbar from "./components/navbar";

const darkergrotesque = Darker_Grotesque({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KONKRET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={darkergrotesque.className}
    >
      <body>
        < Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
